### ISSUE TITLE
AssertionError: Unreordered bidirectional frame occured

### ISSUE THREAD

**Issue by azuryl** [Lijun-Yu/diva_io#3]
ubuntu16.04  cuda10.1

File "/app/divaio/video/reader.py", line 258, in _fix_missing
    'Unreordered bidirectional frame occured.' + self._assert_msg
AssertionError: Unreordered bidirectional frame occured. Please report /home/videos/2018-03-12_10-20-00_10-25-00_bus_G331.avi to Lijun.

**Comment by Lijun-Yu** [comment]
Hi! Thanks for the report. I have reproduced your finding on this video. This assertion occurs when the reorder buffer is not large enough to correct the frame order. Its default value of 5 frames passed the test on the videos of KF1 annotation, but this video would need a larger one. 

Set `buffer_size=30` at [this line](https://github.com/CMU-INF-DIVA/avi-r/blob/master/avi_r/reader.py#L301) would fix it, but may (very) slightly reduce the speed. I'll further test its effect and probably make this a public parameter. Meanwhile, you can use the temporary fix above.

**Comment by azuryl** [comment]
ok I will try it thank you

**Comment by Lijun-Yu** [comment]
The reorder buffer is now re-designed in [v1.1](https://github.com/CMU-INF-DIVA/avi-r/releases/tag/v1.1) with speed improvement. As the package has been renamed and published to [PyPI](https://pypi.org/project/avi-r/), you can install the latest version by

```sh
pip install -U avi-r
``` 
and change the import line in your code from `from diva_io.video import VideoReader` to `from avi_r import AVIReader as VideoReader`.
