### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'height

### ISSUE THREAD

**Issue by azuryl** [Lijun-Yu/diva_io#4]
2018-03-11_16-20-01_16-25-01_school_G339.avi
and
2018-03-12_10-55-01_11-00-01_bus_G509.avi
Traceback (most recent call last):
   video_reader = VideoReader(video_name, video_dir, fix_missing=True)
  File "/app/divaio/video/reader.py", line 59, in __init__
    self.height = self._stream.codec_context.format.height
AttributeError: 'NoneType' object has no attribute 'height'

**Comment by Lijun-Yu** [comment]
These video files are likely to be unrecoverably corrupted. You can verify that by running
```sh
ffmpeg -i <xx.avi> -r 1 <outdir>/%05d.img
```
or open them in a local video player.

**Comment by azuryl** [comment]
you are right ,it can not be played by video player.
thank you
